server:
  port: 3344

spring:
  application:
    name:  springcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FcP9203046931/springcloud-config.git #GitHub上面的git仓库名字


